# Generated by Django 2.2.7 on 2020-02-07 05:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pubdate', models.DateTimeField(default=datetime.datetime(2020, 2, 7, 5, 1, 39, 937574, tzinfo=utc))),
                ('myimage', models.ImageField(null=True, upload_to='images/')),
                ('location', location_field.models.plain.PlainLocationField(max_length=63, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
