# Generated by Django 2.2.7 on 2020-02-04 22:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 22, 57, 26, 123479, tzinfo=utc)),
        ),
    ]
