# Generated by Django 2.2.7 on 2020-02-07 04:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200207_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 4, 38, 56, 390166, tzinfo=utc)),
        ),
    ]
