# Generated by Django 2.2.7 on 2020-02-07 04:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200207_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 4, 58, 50, 574122, tzinfo=utc)),
        ),
    ]
